### ISSUE TITLE
🔴 BUG: White space below find issues tab.

### ISSUE THREAD

**Issue by foxnikean** [ArslanYM/StarterHive#226] opened 2023-06-07 12:06 UTC
There is a white space below the find issues tab.

<img width="1680" alt="image" src="https://github.com/ArslanYM/StarterHive/assets/84733674/fb38d48d-7392-4456-9e3e-e627e55fa351">

I just opened it on a 13 inch macbook air. 

I can handle it if you want.

**Comment by ArslanYM** [comment] 2023-06-07 13:57
@foxnikean Sure thing, Assigned to you.

**Comment by AniketSaraswat112** [comment] 2023-06-08 23:50
HI @ArslanYM @foxnikean tried this in developer tools but this issue is not reproducible on my system. This behaviour might be due to some issue in your laptop, can you try this again @foxnikean pls. Attaching the image from my system.

<img width="959" alt="image" src="https://github.com/ArslanYM/StarterHive/assets/56517011/f049c671-96c0-4d56-9ec7-7cb59ef00a07">

**Comment by foxnikean** [comment] 2023-06-09 16:32
Yes sure it did. This issue can be closed.

**Closed** 2023-06-09 16:32 UTC
Labels: BUG, good first issue, FRONTEND
